onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

overrides:
  typescript: 5.1.6
  '@typescript-eslint/eslint-plugin': 5.62.0
  '@typescript-eslint/parser': 5.62.0
